### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by timsenecal** [bolderflight/sbus#61]
I have tried to use this on a Teensy LC, Teensy 3.1 and Teensy 3.2.

using your example arduino ino sketch,

sbus_rx.read() never returns true, regardless which serial hardware identifier i use, regardless of inv parameter of true or false.

I have tried this with the following sbus receivers:

Frsky x4r-sb
Frsky x8r
Frsky x6r
Jumper r8
Radiomaster r168-d16

in addition, i have verified that the s-bus ports on all the receivers work using the Frsky sbus to pwm decoder.

**Comment by flybrianfly** [comment]
@timsenecal, thanks, I found a bug that was introduced in our last major revision which could hang a Teensy 3.1/3.2 if the *Write* method was called. This is fixed in v8.1.4. I tested against a Teensy 3.0, Teensy 3.2 and Teensy LC and all work.

If it's still not working for you, I would check that the receiver is bound to the transmitter and the transmitter is turned on. I've noticed that the SBUS receivers don't send any packets until the transmitter has been turned on and communicating with the receiver.

**Comment by tursilion** [comment]
On the Uno, found I needed to enable the input pullup to get reliable data from a X8R receiver. Perhaps similar?

**Comment by timsenecal** [comment]
Just for clarification, I am using the receivers with an active bound transmitter, tested using three different models: a home grown model using a 4-in-1 transmitter module (clone d-16 mode), an FrSky Taranis x9d (internal OG accst d-16 module), and a FrSky QX7 (OG accst d-16 module).

**Comment by flybrianfly** [comment]
Should be working. I would try v8.1.4 of the library. If it still isn't working, let's post some photos of our setups and maybe something will stand out.

**Comment by tpsenecal** [comment]
I resolved this issue by completely deleting Arduino IDE and all of its directories from my Ubuntu machine, and re-installing everything.  am now using Arduino 1.8.19, teensyduino and sbus v8.1.4.  It seems to be working now.  not sure if i should try using the new Arduino 2.0.1 IDE or not.  This is using both Teensy LCs (3) and a Teensy 3.2, with FrSky x4rsb (3) and a Radiomaster r168.

**Comment by flybrianfly** [comment]
Glad to hear it’s working. 

I would recommend holding off on Arduino 2.x for now. Teensyduino support is currently in Beta and I haven’t done any testing of BFS libraries against Arduino 2.x yet. I’m waiting for a stable Teensyduino release before I’ll work with Arduino 2.x on my end.
